# Generated by Django 3.2 on 2022-06-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FolderNote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='owner',
            new_name='user',
        ),
    ]
